version: '3.8'

services:
  web:
    image: hello_flask
    container_name: flask
    build: ./
    command: python server.py run -h 0.0.0.0
    volumes:
      - ./app/:/src/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data: